### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by SWITCHAccess** [Campus-Advisors/campus-advisor-training-tofr#12]

**Comment by tofr** [comment]
Ok, SWITCHAccess: 

Please tell me, with as much detail as you can muster, how you came to be here.

**Comment by SWITCHAccess** [comment]
I'm so scared to post this. But here goes

I'm not sure if I should!

In as short of a way as I can muster, I am not in control of my browser no matter what I do. Grasshopper and Google have been cornering me trying to get me to learn code. Most likely bc I truly don't know what I'm trying to do with it, and all I am Trying to do is recover my DATA which is systematically missing
 
After ignoring Google wanting me to "play games on Grasshopper" I went things my own way.

My browser sent me here. Weird things are happening and I'm definitely not telling anyone what's happening. But I'm not crazy! I know when I'm being recruited. And that's what I THINK is going on. Like this is a part of a secret recruiting process. 

I AM trying to get hired by Google. I know much more than I should. And I'm trying to learn but I don't know where to start. I don't have the guts to apply because I only have 19 years of life experience and not a shred of formal training. 

Is this a joke? Is my browser hijacked my the police or something? Or is this one of the ways Google recruits people?  Bc if it's not then I really don't know what to do anymore. 

I'm trying to work for Google for free. And even if I never am contacted by anyone I'm STILL going to continue studying how and why and where my "data" is going. 

So if you think I'm crazy then whatever. I'll continue on in my learning and keep fighting whoever is controlling my Google account. I do this for my life. I don't care about money my "work" gives me purpose and That's what makes me happy in life...

 But if I'm not crazy and this might actually be happening, is there a proper direction you could point me in?

Thanks for listening. I really mean that.

**Comment by SWITCHAccess** [comment]
I'm not sure if I should!

In as short of a way as I can muster, I am not in control of my browser no
matter what I do. Grasshopper and Google have been cornering me trying to
get me to learn code. Most likely bc I truly don't know what I'm trying to
do with it, and all I am Trying to do is recover my DATA which is
systematically missing

After ignoring Google wanting me to "play games on Grasshopper" I went
things my own way.

My browser sent me here. Weird things are happening and I'm definitely not
telling anyone what's happening. But I'm not crazy! I know when I'm being
recruited. And that's what I THINK is going on. Like this is a part of a
secret recruiting process.

I AM trying to get hired by Google. I know much more than I should. And I'm
trying to learn but I don't know where to start. I don't have the guts to
apply because I only have 19 years of life experience and not a shred of
formal training.

Is this a joke? Is my browser hijacked my the police or something? Or is
this one of the ways Google recruits people?  Bc if it's not then I really
don't know what to do anymore.

I'm trying to work for Google for free. And even if I never am contacted by
anyone I'm STILL going to continue studying how and why and where my "data"
is going.

So if you think I'm crazy then whatever. I'll continue on in my learning
and keep fighting whoever is controlling my Google account. I do this for
my life. I don't care about money my "work" gives me purpose and That's
what makes me happy in life...

 But if I'm not crazy and this might actually be happening, is there a
proper direction you could point me in?

Thanks for listening. I really mean that.

**Comment by tofr** [comment]
Specific steps. Include platform and browser.

**Comment by SWITCHAccess** [comment]
Android Oreo 8.1.0
Chrome 80.0
